# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7796cf6de173a1b262c030ade7068d06848e1b324e49dd04636126889569bb65dcde166d9e5f4104e14baa7d5875710a42a49fcfdd32ddbc3fd0f8369cb0c45f

test:
  secret_key_base: 0b56d2673e41df3998ff4ce3e43b10ab0e9add4adf9124b26210d4548ccadc327aa4464d995a5be4f3edcde1664b1e420412d2a31303dbcb4d6599e358068087

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
